version: "3"

services:
  db:
    image: scylladb/scylla:5.1
    ports:
      - 9042:9042
    volumes:
      - scylla_data:/var/lib/scylla

  api:
    build: ./api
    expose:
      - 8081
    depends_on:
      - db

  nginx:
    build: ./nginx
    ports:
      - 81:80
    depends_on:
      - db
      - api

volumes:
  scylla_data: